### PR TITLE
Add a styleguide for testing.

### PR DESCRIPTION
**Pull request by elliotcm**
Much of the fine detail is encoded in our Rails
app templates.  https://github.com/alphagov/govuk-rails-app-template/pull/15

### CODE REVIEW

**Comment by MatMoore** [comment]
👍 

> We discourage too much stubbing in tests with the exception of external services.

Could this be more precise? "Too much" could mean different things to different people...

**Comment by elliotcm** [comment]
@MatMoore I agree, though we need to strike a balance between being too vague and too constricting, since people should be able to apply their own judgement to the situation.

What *do* we consider too much stubbing?

**Comment by benhyland** [comment]
@ecm as a guideline, stubbing and mocking should be used only where you are testing an `effect`, from the point of view of the unit/system under test.

It is useful to note that a unit in the testing sense is not required to be a single class, or code file, or anything in particular - it should simply be a component which it makes sense to test in isolation and which has high internal connascence.

To reduce fragility of tests in the face of future change and to improve the ease of refactoring, it is better to use 'real' code instead of stubs wherever possible otherwise. It helps to think of testing inputs and outputs - to test in terms of things which are already observable at the boundary of your component.

**Comment by elliotcm** [comment]
@benhyland (I'm @elliotcm outside of Slack)

**Comment by benhyland** [comment]
@elliotcm ah sorry. Darn Estuarine and Coastal Modeling Conferences!

The discussion is probably too nuanced for this medium - I'd be happy to continue it in person if the below doesn't help.

I'm using `effects` in the sense of an interaction a system within a delineated boundary has with the outside world. The precise meaning varies depending on the boundary chose, and on the assumptions made about the system context.

For example, in pure functional programming, writing to a file, modifying shared memory, or throwing an exception are all treated as effects, but allocating more memory is usually not treated as an effect even though it might fail if the machine's resources are exhausted - the first 3 are treated as effects due to affecting something outside the boundary of the pure function, while the last is not because of a modelling assumption made to make it simpler to reason about the system in the usual case.

In a Ruby webapp, one might not treat raising an error as an effect because this sort of thing is accepted as normal in the chosen context. However we would probably still expect to stub out http interactions (e.g. with webmock), because the boundary we are working within doesn't subsume the transport layer and the other endpoints we might want to talk to, even if they are really implemented by other controllers within the same process.

**Comment by elliotcm** [comment]
Sure.  But there is a certain practicality at work, that boundary is going to be different for different scales of testing and for different interactions, which makes it hard to put down in writing.

What I'm trying to get out of it is a useful guide for people being introduced to our organisation, but maybe that could just take the form of "think twice before mocking/stubbing" and let code review shape the rest.

**Comment by benhyland** [comment]
Yep, the appropriate boundary to consider will be different for different situations. That's exactly what I was trying to get at (but I put it less succinctly).

I think the guidance should be to consider what boundary is appropriate for a given situation and then to restrict your mocks/stubs to that boundary. I think that education on this topic needs to be endemic and continuous - documentation helps, so does code review, so does ordinary conversation, so do good code examples.

**Pull request merged**
