### PR TITLE
Refer to govuk-lint for the Ruby styleguide

### PR DESCRIPTION
**Pull request by tijmenb**
This removes the Ruby styleguide. Our conventions are already codified in [govuk-lint][], so this is duplicated information. The last actual change to the guide was in [2014][]. All subsequent commits refer to govuk-lint as the source of truth.

[govuk-lint]: https://github.com/alphagov/govuk-lint
[2014]: https://github.com/alphagov/styleguides/commit/a1159040321ed0fc411edef7421cd0081450cbae

### CODE REVIEW

**Comment by alexmuller** [comment]
Also one thing I forgot to add: it would probably be beneficial to rename this from `govuk-lint` to something like `gds_ruby_lint` but given how much effort that will take I suspect it's not worth it.

**Comment by alexmuller** [comment]
https://github.com/alphagov/gds-tech/pull/5

**Comment by boffbowsh** [comment]
I'd be happy to change that repo and gem to be `gds-lint`, the intention (and also the practice) it is to provide a linter for other languages too, not just Ruby. It already covers Sass as well. We could do a shuffle quite easily where the next version of `govuk-lint` simply depends on `gds-lint` and is empty otherwise?

**Comment by fofr** [comment]
Is the same also true for Sass linting and https://github.com/alphagov/styleguides/blob/master/css.md?

**Comment by tijmenb** [comment]
👍  I'll open a new issue on govuk-lint to discuss naming.

**Pull request merged**
