### PR TITLE
Remove GDS tone and context

### PR DESCRIPTION
**Pull request by jabley**
- Replace organisation references with M&S
- Localise to our context

### CODE REVIEW

**Comment by alext** [comment]
I don't think you meant to target this PR at the alphagov repo...

**Comment by jabley** [comment]
Sorry! That'll teach me to use the UI and not the CLI.

**Comment by boffbowsh** [comment]
Awkward.

**Comment by jamiecobbett** [comment]
Do any of you young whippersnappers remember these days: https://github.com/alphagov/publisher/pull/134

**Comment by tommyp** [comment]
Can you do one for Deliveroo while your at it @jabley?

**Comment by jabley** [comment]
@jamiecobbett, are you saying I need to up my game?

**Pull request closed without merging**
