### PR TITLE
Edit Pull Request styleguide

### PR DESCRIPTION
**Pull request by annashipman**
The pull request guidance is currently very long. It contains useful information, but is too long to point people at; it is basically a wall of text.

This is a first stab at cutting it down to the crucial points so it can be a more useful resource. There is certainly more that could be done but I thought it worth making this first step. Explanation of all changes is in each commit message.

I've discussed my intention to do this offline with @daibach and I think it should probably be him who reviews this. Please note, Dai, that I am on leave from 6th January so won't respond to any comments after that; if you are looking at it after that point please feel free to make any changes you think are appropriate.

### CODE REVIEW

**Comment by annashipman** [comment]
Also, I wrote a blog post about how to raise a good PR: http://www.annashipman.co.uk/jfdi/good-pull-requests.html which some other teams have been referring/linking to when commenting on PRs. We could include a link to this if you think it would be useful but thought it would be a bit cheeky just to add it in myself :smile:

**Comment by daibach** [comment]
I think this is really good - it makes the guidance much clearer and simpler to read. 

I think it's worth adding in the link to your blog post - it's useful extra reading. I'll add that to the guide before merging.

Thanks for doing this @annashipman!

**Comment by annashipman** [comment]
:+1: thanks @daibach!

**Comment by dcarley** [comment]
:+1: :+1:

**Pull request merged**
